package com.morainet.mcos.marketplace

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull

/**
 * One wizard question generated by [RecipeInstaller.prepare]
 * ([05-workflow.md §14.1] placeholder binding, [09-marketplace.md §8.3] step 2).
 *
 * @param suggested value read from Memory via `fromMemory`, proposed to the
 *                  user for confirmation or override; null when no memory hit.
 */
data class PlaceholderPrompt(
    val key: String,
    val label: String? = null,
    val required: Boolean = false,
    val suggested: String? = null,
    val default: String? = null,
)

/**
 * The wizard plan for a recipe install ([09-marketplace.md §8.3]).
 */
data class RecipeInstallPlan(
    val missingDependencies: List<MissingDependency>,
    val prompts: List<PlaceholderPrompt>,
) {
    val blockedOnDependencies: Boolean get() = missingDependencies.isNotEmpty()
}

/**
 * Outcome of [RecipeInstaller.submit] ([09-marketplace.md §8.3]).
 */
sealed interface RecipeInstallOutcome {
    /** Dependencies are unsatisfiable; offer a batch install first. */
    data class NeedsDependencies(val missing: List<MissingDependency>) : RecipeInstallOutcome

    /** Required placeholders lack bound values; show the wizard. */
    data class NeedsInput(val prompts: List<PlaceholderPrompt>) : RecipeInstallOutcome

    /** Workflow compiled with all `{{placeholder.*}}` tokens substituted. */
    data class Installed(val recipe: CompiledRecipe) : RecipeInstallOutcome
}

/**
 * A compiled recipe workflow — no `{{placeholder.*}}` tokens remain
 * ([05-workflow.md §14.1]).
 */
data class CompiledRecipe(
    val recipeId: String,
    val version: String,
    val name: String,
    val workflow: JsonObject,
    val triggerPreview: RecipeTriggerPreview? = null,
)

/**
 * A required placeholder had no bound value ([09-marketplace.md §8.3] step 2b).
 */
class RecipeBindingException(message: String) : Exception(message)

/**
 * The workflow referenced an undeclared `{{placeholder.*}}` token, violating
 * the placeholder-completeness gate ([09-marketplace.md §8.1]).
 */
class RecipeCompileException(message: String) : Exception(message)

/**
 * Implements the recipe install wizard ([09-marketplace.md §8.3]): dependency
 * resolution (§7.4) → placeholder prompts with Memory suggestions (§14.1) →
 * IR compilation that substitutes `{{placeholder.key}}` tokens.
 *
 * Registration into the local workflow DB and trigger handling happen
 * upstream; this component is the pure wizard/compile stage.
 */
class RecipeInstaller {

    /**
     * Resolve dependencies and build the placeholder prompt list.
     *
     * @param installedVersion installed version of a plugin id, or null.
     * @param marketplaceLookup marketplace listing for a plugin id, or null.
     * @param memoryLookup value stored at the placeholder's `fromMemory` path,
     *                     or null.
     */
    suspend fun prepare(
        recipe: RecipeEnvelope,
        installedVersion: (String) -> String?,
        marketplaceLookup: suspend (String) -> PackageMetadata?,
        memoryLookup: (String) -> String? = { null },
    ): RecipeInstallPlan {
        val resolveResult = RecipeDependencyResolver.resolve(
            recipe = recipe,
            installedVersion = installedVersion,
            marketplaceLookup = marketplaceLookup,
        )
        val missing = (resolveResult as? RecipeResolveResult.Unresolved)?.missing.orEmpty()

        val prompts = recipe.placeholders.map { placeholder ->
            PlaceholderPrompt(
                key = placeholder.key,
                label = placeholder.label,
                required = placeholder.required,
                suggested = placeholder.fromMemory?.let(memoryLookup),
                default = placeholder.default,
            )
        }
        return RecipeInstallPlan(missingDependencies = missing, prompts = prompts)
    }

    /**
     * Validate bindings and compile the workflow ([09-marketplace.md §8.3]
     * steps 2–3). Non-required placeholders without a binding fall back to
     * their default, then to the empty string; a missing required binding
     * returns [RecipeInstallOutcome.NeedsInput].
     */
    fun submit(
        recipe: RecipeEnvelope,
        plan: RecipeInstallPlan,
        bindings: Map<String, String>,
    ): RecipeInstallOutcome {
        if (plan.blockedOnDependencies) return RecipeInstallOutcome.NeedsDependencies(plan.missingDependencies)

        val missingRequired = plan.prompts.filter { it.required && bindings[it.key].isNullOrBlank() }
        if (missingRequired.isNotEmpty()) return RecipeInstallOutcome.NeedsInput(missingRequired)

        val resolved = plan.prompts.associate { prompt ->
            val bound = bindings[prompt.key]
            val value = when {
                !bound.isNullOrBlank() -> bound
                prompt.default != null -> prompt.default
                else -> ""
            }
            prompt.key to value
        }

        val compiledWorkflow = compile(recipe, resolved)
        return RecipeInstallOutcome.Installed(
            CompiledRecipe(
                recipeId = recipe.recipeId,
                version = recipe.version,
                name = recipe.name,
                workflow = compiledWorkflow,
                triggerPreview = recipe.triggerPreview,
            ),
        )
    }

    /**
     * Recursively replace every `{{placeholder.<key>}}` token in the IR with
     * its bound value. A residual token whose key is not declared in
     * `placeholders` fails the compile ([09-marketplace.md §8.1]).
     */
    fun compile(recipe: RecipeEnvelope, bindings: Map<String, String>): JsonObject {
        val declared = recipe.placeholders.map { it.key }.toSet()
        val replacer: (String) -> String = { text ->
            bindings.entries.fold(text) { acc, (key, value) ->
                acc.replace("{{placeholder.$key}}", value)
            }
        }

        val compiled = substitute(recipe.workflow, replacer) as JsonObject
        val residual = findResidualToken(compiled)
        if (residual != null) {
            if (residual !in declared) {
                throw RecipeCompileException(
                    "SCHEMA_VIOLATION: workflow references undeclared placeholder '$residual'"
                )
            }
            throw RecipeCompileException("placeholder '$residual' was not substituted")
        }
        return compiled
    }

    private fun substitute(element: JsonElement, replacer: (String) -> String): JsonElement = when (element) {
        is JsonObject -> JsonObject(element.mapValues { (_, v) -> substitute(v, replacer) })
        is JsonArray -> JsonArray(element.map { substitute(it, replacer) })
        is JsonPrimitive ->
            if (element.contentOrNull != null) JsonPrimitive(replacer(element.content)) else element
        JsonNull -> element
    }

    private fun findResidualToken(element: JsonElement): String? = when (element) {
        is JsonObject -> element.values.firstNotNullOfOrNull { findResidualToken(it) }
        is JsonArray -> element.firstNotNullOfOrNull { findResidualToken(it) }
        is JsonPrimitive -> element.contentOrNull
            ?.let { TOKEN_REGEX.find(it) }
            ?.groupValues
            ?.getOrNull(1)
        JsonNull -> null
    }

    private companion object {
        // {{placeholder.<key>}} — closing braces escaped: Android's stricter
        // regex engine rejects a bare `}` (reads it as a dangling quantifier),
        // unlike the lenient desktop JVM engine the unit tests run on.
        val TOKEN_REGEX = Regex("\\{\\{placeholder\\.([^}]+)\\}\\}")
    }
}
